name: MyApp
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "16.0"

# Load credentials from xcconfig files
configFiles:
  Debug: Configs/Project.xcconfig
  Release: Configs/Project.xcconfig

settings:
  base:
    # Disabled during development - causes CLI build issues
    ENABLE_HARDENED_RUNTIME: NO
    ENABLE_ENHANCED_SECURITY: NO
    # Xcode 16+ recommended settings
    DEAD_CODE_STRIPPING: YES
    ENABLE_USER_SCRIPT_SANDBOXING: YES
    ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
    SWIFT_EMIT_LOC_STRINGS: YES
    # App metadata
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    INFOPLIST_KEY_CFBundleDisplayName: MyApp
    # Team ID loaded from Configs/Project.xcconfig

packages:
  MyApp:
    path: ../..

targets:
  MyApp:
    type: application
    platform: iOS
    sources:
      - Sources
      - path: Resources/Assets.xcassets
    dependencies:
      - package: MyApp
        product: MyAppCore
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.myapp
        INFOPLIST_FILE: Resources/Info.plist
        SWIFT_VERSION: "6.0"
        GENERATE_INFOPLIST_FILE: false
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon

schemes:
  MyApp:
    build:
      targets:
        MyApp: all
    run:
      config: Debug
      executable: MyApp
    test:
      config: Debug
    profile:
      config: Release
    archive:
      config: Release
