# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=/Users/blacktop/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="sorin"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.

# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(zsh-autosuggestions git docker docker-compose brew cask tmux go httpie node npm nvm nmap osx vault vagrant)

source $ZSH/oh-my-zsh.sh

# User configuration
export TERM="xterm-256color"

# export POWERLINE_RIGHT_B="none"tmux

#source /usr/local/lib/python3.5/site-packages/powerline/bindings/zsh/powerline.zsh

export DEFAULT_USER=blacktop
export PATH=/usr/local/bin:$PATH

# zsh-completions
fpath=(/usr/local/share/zsh-completions $fpath)

# Golang
export GOPATH=~/go
export PATH=$PATH:$GOPATH/bin

# NodeJS
export NVM_DIR="$HOME/.nvm"
. "/usr/local/opt/nvm/nvm.sh"

# VirtualenvWrapper
# export WORKON_HOME=$HOME/.virtualenvs
# export PROJECT_HOME=$HOME/Devel
# source /usr/local/bin/virtualenvwrapper.sh

# Homebrew
export HOMEBREW_EDITOR=atom

# Malice
function domalice () {docker-machine create -d digitalocean --digitalocean-region "sfo1" --digitalocean-size "1gb" malice;eval $(docker-machine env malice)}
fileinfo(){ for x in *; do echo "$(file $x) [md5: $(gmd5sum $x | awk '{ print $1 }')]"; done; }

# Github
export GITHUB_ACCESS_TOKEN=

# Docker
alias dcc='docker-clean stop'
export DOCKER_HIDE_LEGACY_COMMANDS=1
export DIGITALOCEAN_ACCESS_TOKEN=

start-swarm(){
  local NUM_NODES=3
  local LEADER_NODE=node1

  for NODE in $(seq 1 $NUM_NODES); do
    docker-machine start node$NODE
  done;

  docker-machine ssh $LEADER_NODE docker node ls
}

create-swarm(){
  local NUM_NODES=3
  local LEADER_NODE=node1

  for NODE in $(seq 1 $NUM_NODES); do
    docker-machine create --driver virtualbox node$NODE
  done;

  LEADER_IP=`docker-machine ip $LEADER_NODE`

  # initialize swarm
  docker-machine ssh $LEADER_NODE docker swarm init --advertise-addr $LEADER_IP

  # Now let's get the swarm join token for a worker node
  JOIN_TOKEN=`docker-machine ssh $LEADER_NODE docker swarm join-token worker -q`

  # all other nodes join as workers
  for n in $(seq 2 $NUM_NODES); do
    docker-machine ssh node$n docker swarm join --token $JOIN_TOKEN $LEADER_IP:2377
  done;

  # promote node 2 and 3 to master role
  # docker-machine ssh $LEADER_NODE docker node promote node2 node3

  # finally show all nodes
  docker-machine ssh $LEADER_NODE docker node ls
}

rm-swarm(){
  local NUM_NODES=3

  for NODE in $(seq 1 $NUM_NODES); do
    docker-machine rm -f node$NODE
  done;
}

stop-swarm(){
  local NUM_NODES=3

  for NODE in $(seq 1 $NUM_NODES); do
    docker-machine stop node$NODE
  done;
}

# zsh movement
bindkey -e
bindkey '^[[1;5C' forward-word
bindkey '^[[1;5D' backward-word
bindkey '^[a' beginning-of-line
bindkey '^[e' end-of-line

# export MANPATH="/usr/local/man:$MANPATH"

export GREP_COLOR='1;33'

# aliases
alias brewu='brew update;brew upgrade;brew cleanup;brew prune;brew doctor;brew cu --dry;apm upgrade -c false'

if [[ $platform == 'linux' ]]; then
  alias ll='ls -alh --color=auto'
  alias ls='ls --color=auto'
elif [[ $platform == 'darwin' ]]; then
  alias ll='ls -alGh'
  alias ls='ls -Gh'
fi
# zsh profile editing
alias ze='vim ~/.zshrc'
# zsh profile reloading
alias zr='source ~/.zshrc'

alias ka9='killall -9'
alias k9='kill -9'

# Finder
alias showFiles='defaults write com.apple.finder AppleShowAllFiles YES; killall Finder /System/Library/CoreServices/Finder.app'
alias hideFiles='defaults write com.apple.finder AppleShowAllFiles NO; killall Finder /System/Library/CoreServices/Finder.app'

source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# You may need to manually set your language environment
export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='atom'
fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
export PATH="/usr/local/sbin:$PATH"
